[build]
builder = "nixpacks"
buildCommand = "cd server && npx prisma generate && npx prisma migrate deploy && cd .. && pnpm run build"

[deploy]
startCommand = "node server/src/index.js"
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

