[build]
builder = "nixpacks"
buildCommand = "cd server && npx prisma generate && cd .. && pnpm run build"

[deploy]
startCommand = "node server/src/index.js"
healthcheckPath = "/health/db"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"

