-- Insertar categorías para el foro
INSERT INTO "Categoria" ("etiqueta") VALUES 
('Voluntariado'),
('Medio-Ambiente'),
('Donacion'),
('Niños'),
('Educacion'),
('Limpieza'),
('Salud'),
('Ancianos'),
('Animales'),
('Comunidad'),
('Emergencias'),
('Cultura'),
('Deportes'),
('Tecnologia'),
('Arte'),
('Musica'),
('Cocina'),
('Jardineria'),
('Construccion'),
('Transporte'),
('Eventos'),
('Reciclaje'),
('Conservacion'),
('Bienestar'),
('Familia');
