erDiagram

    RolUsuario{
        int id_rol PK
        int id_usuario FK
        string nombre_RolUsuario
    }
    Usuario{
        int id_usuario PK
        string usuario
        string telefono
        string correo
        string contrasena
    }
    ONGxToken{
        int id_token PK
        int id_usuario FK
        string token
    }
    Ranking{
        int id_ranking PK
        int id_tipo_ranking
        int id_pedido FK
        int puesto
        int puntos
    }
    TipoRanking{
        int id_tipo_ranking
        string tipo_ranking
    }
    Donacion {
        int id_donacion PK
        string tipo_donacion
        string descripcion
        int puntos
    }
    Publicacion {
        int id_publicacion PK
        int id_usuario FK
        string direccion_pick_up
        string titulo
        string descripcion
        date fechaAlta
        date fechaBaja
        img imagen
    }
    Categoria {
        int id_categoria PK
        string etiqueta
    }
    PublicacionCategoria {
        int id_publicacion_categoria PK
        int id_publicacion FK
        int id_categoria FK
    }
    RespuestaPublicacion {
        int id_respuesta PK
        int id_publicacion FK
        int id_usuario FK
        string mensaje
        date fecha
    }
    PedidoDonacion {
        int id_pedido PK
        int id_publicacion_categoria FK
        int id_rol FK
        int id_donacion FK
        string descripcion
        int cantidad
        date fecha
    }

    
    RolUsuario ||--|{ ONGxToken: tiene
    RolUsuario ||-- || Usuario: "tiene un"
    RolUsuario ||--|{ Publicacion : publica
    Publicacion ||--|{ PublicacionCategoria : tiene
    Categoria ||--|{ PublicacionCategoria : clasifica
    PublicacionCategoria ||--|{ PedidoDonacion : tiene
    RespuestaPublicacion }|--|| PublicacionCategoria : tiene
    RolUsuario ||--|{ RespuestaPublicacion: tiene
    RolUsuario ||--|{ PedidoDonacion : realiza
    PedidoDonacion }|--|| Donacion : clasifica
    PedidoDonacion ||--|{ Ranking : clasifica
    TipoRanking ||--|{Ranking: tiene